apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  env-config.js: |
    window.env = {
      API_URL: "http://a78fbd9c9cf9242d9a92bedcc7941a44-d66c5ebf896d626e.elb.us-east-1.amazonaws.com/api"
    };
