apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
  labels:
    app: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: 211125549407.dkr.ecr.us-east-1.amazonaws.com/kubes/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql-service"    # Update if your DB service name differs
            - name: DB_USER
              value: "your_db_user"
            - name: DB_PASSWORD
              value: "your_db_password"
            - name: DB_NAME
              value: "your_db_name"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend
spec:
  type: LoadBalancer
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
