name: Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - pod
          - prod
      region:
        description: "Select AWS region"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-west-2
          - us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_ENV: ${{ github.event.inputs.env }}
      AWS_REGION: ${{ github.event.inputs.region }}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS credentials from single account (GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Terraform Init with fixed backend bucket
      - name: Terraform Init
        run: |
          cd iac_tf
          terraform init -reconfigure \
            -backend-config="bucket=my-terraform-state-us-east1-unique" \
            -backend-config="key=terraform/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="encrypt=true"

      # Terraform Workspace (optional)
      - name: Select/Create Terraform Workspace
        run: |
          cd iac_tf
          terraform workspace select $TF_ENV || terraform workspace new $TF_ENV

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          cd iac_tf
          terraform plan -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd iac_tf
          terraform apply -auto-approve tfplan
