name: IAC_Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 3. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 4. Terraform Fmt
      - name: Terraform Fmt
        run: terraform fmt -recursive

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # 7. Approval before Apply
      - name: Wait for Approval
        environment: production
        run: echo "Waiting for manual approval..."

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
