name: Terraform Infrastructure

on:
  workflow_dispatch: # Manual trigger

jobs:
  # Job 1: Create S3 backend bucket
  create-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Terraform backend S3 bucket
        run: |
          aws s3api create-bucket \
            --bucket my-terraform-state-us-east1 \
            --region us-east-1 || echo "Bucket already exists"

  # Job 2: Terraform Plan
  plan:
    needs: create-backend
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          cd iac_tf
          terraform init -reconfigure

      - name: Terraform Plan
        id: plan
        run: |
          cd iac_tf
          terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: iac_tf/tfplan

  # Job 3: Terraform Apply (manual approval)
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: terraform-apply  # GitHub Environment with required approval
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: iac_tf/

      - name: Terraform Apply
        run: |
          cd iac_tf
          terraform apply -auto-approve tfplan
