name: Terraform Infrastructure

on:
  workflow_dispatch: # Manual trigger

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Terraform Init
      - name: Terraform Init
        run: |
          cd iac_tf
          terraform init -reconfigure

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          cd iac_tf
          terraform plan -out=tfplan

      # Upload Plan Artifact
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: iac_tf/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: terraform-apply
      # Requires manual approval in GitHub environment

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Download Plan Artifact
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: iac_tf/

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd iac_tf
          terraform apply -auto-approve tfplan
